export const LOAD_WEATHER = "LOAD_WEATHER";
export const START_LOAD_WEATHER = "START_LOAD_WEATHER";
export const LOAD_WEATHER_SUCCESS = "LOAD_WEATHER_SUCCESS";
export const LOAD_WEATHER_ERROR = "LOAD_WEATHER_ERROR";
export const SET_WEATHER_PROVIDER = "SET_WEATHER_PROVIDER";
export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";
export const SET_FORECAST_TYPE = "SET_FORECAST_TYPE";

export default {LOAD_WEATHER, START_LOAD_WEATHER, LOAD_WEATHER_SUCCESS, LOAD_WEATHER_ERROR, SET_WEATHER_PROVIDER, SET_START_DATE, SET_END_DATE, SET_FORECAST_TYPE}

